# Generated by Django 6.0.2 on 2026-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='cleaned_description',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
