# Generated by Django 5.1.7 on 2026-02-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_vacancy_options_remove_vacancy_employer_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='users.employerprofile', verbose_name='Работодатель'),
            preserve_default=False,
        ),
    ]
