# Generated by Django 5.1.7 on 2026-02-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_vacancy_employer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Описание и требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='users.employerprofile'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название должности'),
        ),
    ]
