# Generated by Django 5.1.7 on 2026-02-25 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_vacancy_options_vacancy_salary_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('ai_data', models.JSONField(verbose_name='Результат ИИ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
