# Generated by Django 5.1.7 on 2026-02-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.IntegerField(verbose_name='Процент совпадения')),
                ('has_skills', models.JSONField(default=list, verbose_name='Совпавшие навыки')),
                ('missing_skills', models.JSONField(default=list, verbose_name='Недостающие навыки')),
                ('ai_recommendation', models.TextField(blank=True, verbose_name='План развития')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='users.studentprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='career.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
